Repository fusionjs/create-fusion-app, pull requests merged in 2019-02, with the labels that each got.

#63 Don't open a browser window when running tests
  test-utils/test-utils.js
Labels: refactor

#64 Upgrade dependencies and add universal events
  package.json
  templates/basic/content/package.json
  templates/basic/content/yarn.lock
  yarn.lock
Labels: bugfix, greenkeeping

#65 Release v0.0.6-0
  package.json
Labels: release

#68 Release v0.0.6
  package.json
Labels: release
